// lib/promptBuilder.js

export function buildTryOnPrompt(modelDescription, clothingDescription, view = "front") {
  if (view === "back") {
    return `Generate a realistic, high-resolution image of a model from the back, wearing a specific clothing item, based solely on the two reference images provided. Show the model’s back view while accurately reproducing the clothing item’s back details, structure, and fit. Maintain the exact skin tone, body shape, hair, and posture from the original model. Ensure the back side of the clothing is logically consistent with the front view design (as seen in the reference). The image should have a clean, light background and studio lighting. Focus only on recreating the correct form of the model wearing the outfit. Avoid generating any accessories, props, text, or extra elements. Do not change the clothing or the model in any way. Do not hallucinate or invent new design aspects. All elements must come only from the two reference images.`.trim();
  }

  return `Generate a realistic, high-resolution image of a model wearing a specific clothing item, using only the provided reference images. The image should show the model from the front, wearing the exact clothing item from the second reference. Recreate the precise appearance, fit, and fabric behavior as seen in the clothing image. The model must retain all original features — face, skin tone, hairstyle, body type, posture, and proportions — exactly as shown in the model reference. Use neutral, light background with soft studio-style lighting. The composition must be clear and focused on the subject. Do not alter the clothing design, material, pattern, color, or cut. Do not add any accessories or props. Do not change the model’s appearance. Do not hallucinate new elements. Do not include text, branding, or irrelevant background content. The generated image must closely resemble the two references combined — the original model wearing the original clothing`.trim();
}
